### ISSUE TITLE
Machine enrollment Screen

### ISSUE THREAD

**Issue by flaviostutz** [labbsr0x/convid-agent-windows#1]
Input:
  - Server address
  - Account email

Button: REGISTER MACHINE

Output:
  - Machine Id
  - Connection status

**Comment by tiagostutz** [comment]
What is "Connection status"?

**Comment by flaviostutz** [comment]
It’s a state indicating if the agent is connected to the cloud or not. Something like a “green” dot...

**Comment by tiagostutz** [comment]
Ok, but I don’t get why it would be part of the enrollment response... isn’t it something that will be evaluated once the SSH connection is successfully made?
