### ISSUE TITLE
Chiquinho: Adjust front end response on ConnectionError

### ISSUE THREAD

**Issue by ggrcha** [labbsr0x/convid-agent-windows#19]
When the backend emits a "ConnectionError" event while trying to create the ssh tunnel, the frontned breaks up.

**Comment by ralphg6** [comment]
@ggrcha this error persists yet?

**Comment by ralphg6** [comment]
@tiagostutz @ggrcha  Can I work with this?

**Comment by tiagostutz** [comment]
Sorry, I was already working on that but forgot to assign.
