### ISSUE TITLE
Machine Enrollment Model

### ISSUE THREAD

**Issue by flaviostutz** [labbsr0x/convid-agent-windows#4]
Provide Go funcs:
  - for enrolling a new Machine (POST /account/[accountId]/machine)
  - for keeping SSH tunnel connections active (reconnect, get newer machine data) and generating events to notify "reconnecting","connected","disconnected".

**Comment by tiagostutz** [comment]
@ralphg6 can we define an interface here so I can code the Frontend invoking those functions?

**Comment by ralphg6** [comment]
@tiagostutz yes! Any suggestion?

The service must invoke the code:
https://github.com/labbsr0x/convid-agent-windows/blob/17936aea2ce4031b61b8a94f6d7b11280dd6f0f8/enrollment-application/enrollment.go#L17

**Comment by tiagostutz** [comment]
@ralphg6 for the second item of this issue (keeping SSH tunnel), you will need issue #6 to be completed... you could also check https://github.com/jairsjunior/go-ssh-client-tunnel

**Comment by ralphg6** [comment]
> @ralphg6 so you could Bind a function for the JS
> 
> ```
> doRegister(address string, account string)
> ```
> 
> In the JS part I'll invoke `window.backend.doRegister(address, account_email)`
> 
> Ok?

@tiagostutz the account is organization accountId.... Right?

**Comment by ralphg6** [comment]
For example: account = "banco-do-brasil"

**Comment by tiagostutz** [comment]
Nope, this is the Organization registered e-mail... it is a kind of `id` because it is unique, but it is not the Mongo generated `id`...

**Comment by tiagostutz** [comment]
E-mail is a more easy to remember information than an account name...
For example: account = "suporte@cvc.com.br"

**Comment by ralphg6** [comment]
But in UX terms, I guess that a text identifier can be easier and intuitive for the users.

**Comment by ralphg6** [comment]
Like organization name here in github! labbsr0x or bancodobrasil!!!

**Comment by tiagostutz** [comment]
How about CNPJ?

**Comment by ralphg6** [comment]
An email can create confusion because the user may believe it must be their own.

**Comment by ralphg6** [comment]
A CNPJ is predictable. In terms of security, it does not seem interesting since it is easy to deduct ... And for companies with more than one CNPJ can also generate confusion ...

**Comment by ralphg6** [comment]
So I think a simple text without meaning that can be passed by a simple text message, for the most interesting.

**Comment by tiagostutz** [comment]
> An email can create confusion because the user may believe it must be their own.
That's right. But a company identification name is one more thing for the customer to keep track of. 

> A CNPJ is predictable. In terms of security, it does not seem interesting since it is easy to deduct
I don't get the security issue. What the user can do?

> And for companies with more than one CNPJ can also generate confusion ...
I disagree... in the worst scenario the user would try 2, 3 CNPJs..

I really didn't want to give one more thing for the user to keep track of...

**Comment by tiagostutz** [comment]
I'm changing the code part here from `accountEmail` to `accountId` and, for now, I'm changing the UI from `e-mail` to `CNPJ`... we decide later after the first customers use the solution.

So, I'll pass an `accountId` as you proposed.

**Comment by ralphg6** [comment]
Ok! Then it can be the CNPJ. Only I guess bit usual.

**Comment by ralphg6** [comment]
> I'm changing the code part here from `accountEmail` to `accountId` and, for now, I'm changing the UI from `e-mail` to `CNPJ`... we decide later after the first customers use the solution.
> 
> So, I'll pass an `accountId` as you proposed.

LGTM!

**Comment by tiagostutz** [comment]
BTW in en-US locale the label is "Organization Login" and in pt-BR I put "CNPJ" 
XD

**Comment by tiagostutz** [comment]
Further improvements should be addressed in specific issues. So far so good.
